# Generated by Django 3.2.4 on 2021-08-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
    ]
